config/routes.rb
  Rails.application.routes.draw do

  resources :notifications, :only => [:create, :destroy]

  root      'locations#index'

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :locations

  resources :beers

  resources :favorites,      only: [:new, :create, :destroy]

  resources :beer_matches,   only: [:create]
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  has_many :favorites
  has_many :beer_matches
  has_many :locations, :through => :beer_matches
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :label_url, :description, :beer_type, :brewery)
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_beer.html.erb
 <%= link_to favorites_path(beer_id: beer.id), method: :post, remote: true do %>
  <div class="list-group-item beer-panel" id="beer_<%= beer.id %>">
    <h3 class="beer-name"><%= beer.name %></h3>
    <h4 class="brewery"><%= beer.brewery %></h4>
    <h5 class="beer-type"><%= beer.beer_type %></h5>
  </div>
<% end %>

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :label_url %><br>
    <%= f.text_field :label_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :beer_type %><br>
    <%= f.text_field :beer_type %>
  </div>
  <div class="field">
    <%= f.label :brewery %><br>
    <%= f.text_field :brewery %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<div>
<div align="center">
  <form>
  <input type="text" placeholder="Search by Name, Brewery, Style" required>
  <input type="button" value="Search">
</form>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-6">
        <div class="panel panel-default">

  <div class="panel-heading">List of Beers</div>
  <div class="panel-body">
  </div>
  <table class="table table-striped">
    <tr>
            <th>Name</th>
            <th>Brewery</th>
            <th>Type of Beer</th>
          </tr>
          <% @beers.each do |beer| %>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.brewery %></td>
            <td><%= beer.beer_type %></td>
          </tr>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.brewery %></td>
            <td><%= beer.beer_type %></td>
          </tr>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.brewery %></td>
            <td><%= beer.beer_type %></td>
          </tr>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.brewery %></td>
            <td><%= beer.beer_type %></td>
          </tr>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.brewery %></td>
            <td><%= beer.beer_type %></td>
          </tr>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.brewery %></td>
            <td><%= beer.beer_type %></td>
          </tr>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.brewery %></td>
            <td><%= beer.beer_type %></td>
          </tr>
          <tr>
            <<td><%= beer.name %></td>
            <td><%= beer.brewery %></td>
            <td><%= beer.beer_type %></td>
          </tr>
          </table>
      </div>
      </div>
        <div class="col-md-6">
        <div class="panel panel-default">

  <div class="panel-heading">Beers selected</div>
  <div class="panel-body">
  </div>
  <table class="table table-striped">
          <tr>
            <th>Beer</th>
            <th>Brewery</th>
            <th>Type of Beer</th>
          </tr>
          <% @beers.each do |beer| %>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.brewery %></td>
            <td><%= beer.beer_type %></td>
          </tr>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.brewery %></td>
            <td><%= beer.beer_type %></td>
          </tr>
          <tr>
            <td><%= beer.name %></td>
            <td><%= beer.brewery %></td>
            <td><%= beer.beer_type %></td>
          </tr>
  </table>
</div>
</div>
    </div>
</div>

<div>
<div align="right">
<form>
  <input class="btn btn-default" type="submit" value="Submit">
</form>
</div>
end

app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Label url:</strong>
  <%= @beer.label_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @beer.description %>
</p>

<p>
  <strong>Beer type:</strong>
  <%= @beer.beer_type %>
</p>

<p>
  <strong>Brewery:</strong>
  <%= @beer.brewery %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>