config/routes.rb
  Rails.application.routes.draw do

  resources :notifications, :only => [:create, :destroy]

  root      'locations#index'

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :locations

  resources :beers

  resources :favorites,      only: [:new, :create, :destroy]

  resources :beer_matches,   only: [:create]
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :name, presence: true
  validates :address, presence: true

  has_many :beer_matches
  has_many :beers, :through => :beer_matches

  geocoded_by :address
  after_validation :geocode
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index

    @user = user_signed_in? ? current_user : User.new

    @beers = Beer.all
    @favorites = @user.favorites

    @favorite_beers = @favorites.collect { |favorite| favorite[:beer_id]}
    @beer_matches = BeerMatch.where(:beer_id => @favorite_beers).collect { |match| match[:location_id]}
    @beer_match_locations = Location.where(:id => @beer_matches)
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :address)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/_signin_modal.html.erb
<div class="modal fade" id="signinModal" tabindex="-1" role="dialog" aria-labelledby="user signin" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
      </div>
      <%= form_for @user, url: user_session_path, method: :post do |f| %>
        <div class="modal-body">
          <div class="row form-group col-sm-8 col-sm-offset-2">
            <%= f.label :email, class: 'control-label' %>
            <%= f.email_field :email, class: 'form-control', autofocus: 'autofocus', placeholder: 'Enter an email', value: nil %>
          </div>

          <div class="row form-group col-sm-8 col-sm-offset-2">
            <%= f.label :password, class: 'control-label' %>
            <%= f.password_field :password, class: 'form-control', autofocus: 'autofocus', placeholder: 'At least 8 characters...' %>
          </div>

          <div class="row form-group col-sm-8 col-sm-offset-2">
            <%= f.label :password_confirmation, class: 'control-label' %>
            <%= f.password_field :password_confirmation, class: 'form-control', autofocus: 'autofocus' %>
          </div>
        </div>
        <div class="modal-footer">
          <div class="col-sm-8 col-sm-offset-2 text-center form-buttons">
            <%= f.submit "Submit", class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/locations/_signup_modal.html.erb
<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="user signup" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
      </div>
      <%= form_for @user, url: user_registration_path, method: :post do |f| %>
        <div class="modal-body">
          <div class="row form-group col-sm-8 col-sm-offset-2">
            <%= f.label :email, class: 'control-label' %>
            <%= f.email_field :email, class: 'form-control', autofocus: 'autofocus', placeholder: 'Enter an email...', value: nil %>
          </div>

          <div class="row form-group col-sm-8 col-sm-offset-2">
            <%= f.label :password, class: 'control-label' %>
            <%= f.password_field :password, class: 'form-control', autofocus: 'autofocus', placeholder: 'At least 8 characters...' %>
          </div>

          <div class="row form-group col-sm-8 col-sm-offset-2">
            <%= f.label :password_confirmation, class: 'control-label' %>
            <%= f.password_field :password_confirmation, class: 'form-control', autofocus: 'autofocus' %>
          </div>
        </div>
        <div class="modal-footer">
          <div class="col-sm-8 col-sm-offset-2 text-center form-buttons">
            <%= f.submit "Submit", class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/locations/_startup_modal.html.erb
<div class="modal fade" id="startupModal" tabindex="-1" role="dialog" aria-labelledby="user-startup" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="user-startup">Interested in being notified when someone finds your beer?</br>Signup now!</h4>
        <h4 class="text-center"><small>or <%= link_to "try as guest", user_registration_path, method: :post %></small></h4>
      </div>
      <%= form_for @user, url: user_registration_path, method: :post do |f| %>
        <div class="modal-body">
          <div class="row form-group col-sm-8 col-sm-offset-2">
            <%= f.label :phone, class: 'control-label' %>
            <%= f.telephone_field :phone, class: 'form-control', autofocus: 'autofocus', placeholder: 'Enter a phone number...' %>
          </div>

          <div class="row form-group col-sm-8 col-sm-offset-2">
            <%= f.label :password, class: 'control-label' %>
            <%= f.password_field :password, class: 'form-control', autofocus: 'autofocus', placeholder: 'At least 8 characters...' %>
          </div>

          <div class="row form-group col-sm-8 col-sm-offset-2">
            <%= f.label :password_confirmation, class: 'control-label' %>
            <%= f.password_field :password_confirmation, class: 'form-control', autofocus: 'autofocus' %>
          </div>
        </div>
        <div class="modal-footer">
          <div class="col-sm-8 col-sm-offset-2 text-center form-buttons">
            <%= f.submit "Submit", class: "btn btn-success" %>
            <h4><small>or <%= link_to "sign in", new_user_session_path %></small></h4>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class="dashboard">
  <div class="col-md-8 map-div">
    <div id="map"></div>
    <button type="button" class="btn btn-primary" id="tip-btn">Did you make a find?</button>
    <%= form_tag beer_matches_path, id: "tip-box", remote: true do %>
      <%= hidden_field_tag :latitude, "", id: "latitude" %>
      <%= hidden_field_tag :longitude, "", id: "longitude" %>
      <%= select_tag 'beer', options_from_collection_for_select(@beers, "id", "name"),
                              include_blank: false, class: "form-control" %>

      <%= text_field_tag 'location', nil, class: "form-control",
                          placeholder: "Where was it?",
                          onclick: "getLocation()"  %>
      <%= submit_tag value = "Leave a tip!", id: "tip-submit", class: "btn btn-primary col-xs-10" %>
      <button class="col-xs-2 close-tip" id="close-tip-btn">
        <%= icon('times', '', class: "fa-lg") %>
      </button>
    <% end %>
    <div class="shade">
      <button type="button" class="btn btn-danger" id="back-btn">
        <i class="fa fa-times fa-lg"></i>
      </button>

      <div class="col-xs-offset-1 col-xs-10 beer-div">
        <div class="list-group beer-list">
          <%= render @beers %>
        </div>
      </div>

    </div>
  </div>
  <div class="col-md-4 menu">

    <div class="row">
      <div class="col-xs-12">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message,
                            class: "alert alert-#{message_type}") %>
        <% end %>
      </div>

      <div class="col-xs-12 favorites-div">
        <div class="list-group favorites-list">
          <%= render @favorites %>
        </div>
      </div>
    </div>

    <div class="main-button-group">
      <button type="button" class="btn btn-default btn-add" id="new-beers-btn">
        <%= icon('plus', '', class: "fa-lg") %>
      </button>
      <div class="signup-signin">
        <% if current_user.guest? %>
        <button type="button" class="btn btn-primary btn-signup" data-toggle="modal" data-target="#signupModal">
          Become a member
        </button>
        <button type="button" class="btn btn-info btn-signin" data-toggle="modal" data-target="#signinModal">
          Log In
        </button>
        <% else user_signed_in? %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-signout" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'signup_modal' %>
<%= render 'signin_modal' %>

<script type="text/javascript">
  window.Matches = <%= @beer_match_locations.to_json.html_safe %>;
  var $latitudeField = $("#latitude");
  var $longitudeField = $("#longitude");

  <% unless user_signed_in? %>
    $(document).ready( function() {
      $('#startupModal').modal('show');
    });
  <% end %>
</script>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>